name: Test Secrets

on: [workflow_dispatch]

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify DOCKER_USERNAME secret
        run: echo "DOCKER_USERNAME is set"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Verify DOCKER_PASSWORD secret
        run: echo "DOCKER_PASSWORD is set"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get short SHA
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Print short SHA
        run: echo "Short SHA is $SHORT_SHA"